defaults: &defaults
  docker:
    - image: circleci/node:12.3.1
  working_directory: ~/repo

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          name: Restore git history
          keys:
            - git-v1-{{ .Branch }}-{{ .Revision }}
            - git-v1-{{ .Branch }}-
            - git-v1-
      - checkout
      - save_cache:
          name: Cache git history
          key: git-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'
      - persist_to_workspace:
          root: .
          paths:
            - .git

  dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-deps-v1-{{ .Branch }}
            - node-deps-v1-
      - run:
          name: Install NPM dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run build

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run test:coverage

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run linting
          command: yarn run lint

worflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
