version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.3.1
    working_directory: /app

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          paths:
            - .git

  dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-deps-v1-{{ .Branch }}
            - node-deps-v1-
      - run:
          name: Install NPM dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run build

  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn run test:coverage

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run linting
          command: yarn run lint

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
